# Generated by Django 3.0.5 on 2020-05-06 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200505_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='currency_from',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub'), ('eur', 'eur')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='currency_to',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub'), ('eur', 'eur')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to=settings.AUTH_USER_MODEL),
        ),
    ]
