# Generated by Django 3.0.5 on 2020-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200506_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='user_to',
            new_name='payee',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='currency_from',
            new_name='payee_currency',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='user',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='currency_to',
            new_name='senders_currency',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Date creation'),
        ),
    ]
